name: fake-news-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.24.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - nltk>=3.8
  - jupyter>=1.0.0
  - notebook>=7.0.0
  - streamlit>=1.25.0
  - plotly>=5.15.0
  - flask>=2.3.0
  - flask-cors>=4.0.0
  - wordcloud>=1.9.0
  - textstat>=0.7.3
  - tqdm>=4.65.0
  - openpyxl>=3.1.0
  - xlrd>=2.0.0
  - gunicorn>=21.2.0
  - python-dotenv>=1.0.0
  - joblib>=1.3.0
  - statsmodels>=0.14.0
  - pillow>=9.5.0
  - pip
  - pip:
    - PyJWT>=2.8.0
    - werkzeug>=2.3.0
    - transformers>=4.30.0
    - datasets>=2.10.0
    - torch>=2.0.0
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
